#!/usr/bin/env python3
"""
Generate inputs.json — the single shared fixture source for the GLYPH
8-scenario cross-language gauntlet.

Every language runner (Python, JS, Go) reads this exact file, so all three
operate on byte-identical inputs ("same conditions"). Re-run after editing:

    python3 gauntlet/scenarios/gen_inputs.py

The data is deliberately *realistic AI-workflow state* (session snapshots,
tool-call traces, match/patch streams, a tool firewall) rather than synthetic
edge cases, while staying inside the JS-safe numeric domain for the checks that
demand byte-for-byte cross-language parity (ints > 2^53 are a documented
divergence, not a conformance target).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "inputs.json")


def tool_trace(n):
    """A homogeneous tool-call trace — the canonical 'repeated records' case."""
    tools = ["search", "fetch", "summarize", "rank", "write_file"]
    rows = []
    for i in range(n):
        rows.append({
            "step": i,
            "tool": tools[i % len(tools)],
            "status": "ok" if i % 7 else "error",
            "ms": (i * 13) % 500,
        })
    return rows


INPUTS = {
    "_meta": {
        "note": "Shared fixtures for the GLYPH 8-scenario cross-language gauntlet. "
                "Generated by gen_inputs.py — do not hand-edit.",
        "numeric_domain": "JS-safe (|int| <= 2^53) for all cross-language byte-parity checks.",
    },

    # S1 — JSON bridge round-trip fidelity. Realistic agent memory snapshot:
    # nested, unicode, nulls, bool, negative int, float, empty string.
    "S1_json_bridge": {
        "snapshot": {
            "session_id": "sess-2026-06-21",
            "turn": 7,
            "model": "claude-opus-4-8",
            "temperature": 0.2,
            "active": True,
            "parent": None,
            "note": "café ☕ — résumé λ",
            "empty": "",
            "tags": ["search", "plan", "act"],
            "budget": {"input_tokens": 12000, "output_tokens": 3500, "remaining": None},
            "offset": -42,
            "steps": [
                {"i": 1, "tool": "search", "ok": True},
                {"i": 2, "tool": "fetch", "ok": False},
            ],
        }
    },

    # S2 — Canonicalization determinism + cross-language agreement.
    # Three key-orderings of one logical object must all canonicalize identically
    # (within a language) and the canonical string must match across languages.
    # `floats_text` exercises number-format parity via the loose-text parser.
    "S2_canonical": {
        "variants": [
            {"action": "search", "query": "weather in Chicago",
             "max_results": 5, "filters": {"lang": "en", "safe": True}, "cursor": None},
            {"cursor": None, "max_results": 5, "query": "weather in Chicago",
             "filters": {"safe": True, "lang": "en"}, "action": "search"},
            {"filters": {"lang": "en", "safe": True}, "action": "search",
             "cursor": None, "query": "weather in Chicago", "max_results": 5},
        ],
        "floats_text": ["1.23e-9", "3.14159", "1000000.0", "-0.0", "0.5", "100", "-7"],
    },

    # S3 — State fingerprint identity, sensitivity & cross-language parity.
    "S3_fingerprint": {
        "base":  {"id": "agent-1", "turn": 3, "scratch": None,
                  "mem": {"a": 1, "b": 2}, "log": ["start", "search"]},
        "equiv": {"log": ["start", "search"], "mem": {"b": 2, "a": 1},
                  "scratch": None, "turn": 3, "id": "agent-1"},
        "mutated": {"id": "agent-1", "turn": 4, "scratch": None,
                    "mem": {"a": 1, "b": 2}, "log": ["start", "search"]},
    },

    # S4 — Tabular packing compaction + recovery + cross-language parity.
    "S4_tabular": {
        "trace": tool_trace(50),
        "min_savings_vs_json": 0.40,
    },

    # S5 — Patch apply correctness (set / append / delete / numeric-delta).
    "S5_patch_apply": {
        "base": {"id": "match:001", "minute": 0, "score_home": 0, "score_away": 0,
                 "events": ["kickoff"], "status": "live", "var_check": True},
        "patch_text": "@patch @target=match:001\n= status finished\n~ minute +90\n+ events Goal\n- var_check\n@end",
        "expected": {"id": "match:001", "minute": 90, "score_home": 0, "score_away": 0,
                     "events": ["kickoff", "Goal"], "status": "finished"},
    },

    # S6 — Standalone patch base verification / fail-closed.
    # State carries a null (last_goal) — the case where the no-tabular fingerprint
    # basis (∅) and the CanonicalizeLoose basis (_) diverge across languages.
    "S6_patch_base": {
        "state": {"id": "match:001", "minute": 45, "score_home": 1,
                  "score_away": 0, "last_goal": None},
        "patch_op_lines": ["= minute 90"],
        "target": "match:001",
        "stale_base": "deadbeefdeadbeef",
    },

    # S7 — GS1 stream framing: wire parity + decode round-trip + base-enforced cursor.
    # Fixed opaque payloads so byte-for-byte Go==JS comparison isolates the framing
    # layer (canonical-text parity is S2/S4's job).
    "S7_gs1_stream": {
        "sid": 42,
        "frames": [
            {"kind": "doc",   "seq": 0, "payload": "{a=1 b=2}"},
            {"kind": "row",   "seq": 1, "payload": "Row@(id 1 name foo)"},
            {"kind": "patch", "seq": 2, "payload": "@patch\n= a 9\n@end"},
            {"kind": "ui",    "seq": 3, "payload": "Progress@(pct=0.5)"},
            {"kind": "ack",   "seq": 4, "payload": ""},
            {"kind": "err",   "seq": 5, "payload": "Err@(code FAIL)"},
            {"kind": "ping",  "seq": 6, "payload": ""},
            {"kind": "pong",  "seq": 7, "payload": ""},
            {"kind": "doc",   "seq": 8, "payload": "done", "final": True},
        ],
        "base_state": {"x": 1, "y": 2},
        "base_patch_payload": "@patch\n= x 2\n@end",
    },

    # S8 — Streaming validator / tool firewall (early rejection) + verdict parity.
    # The validator consumes each implementation's native tool-call syntax
    # (JS: {action=tool ...}; Py: tool{...}); the *verdict* must agree.
    "S8_firewall": {
        "allowed_tool": "search",
        "blocked_tool": "wire_transfer",
        "allowed_js": '{action=search query="latest weather in Chicago" max_results=5}',
        "blocked_js": "{action=wire_transfer amount=1000000 target=unknown}",
        "allowed_py": 'search{query="latest weather in Chicago" max_results=5}',
        "blocked_py": "wire_transfer{amount=1000000 target=unknown}",
        "registry": {
            "search": {"query": "str", "max_results": "int"},
            "calculate": {}, "browse": {}, "execute": {},
            "read_file": {}, "write_file": {},
        },
    },
}


def main():
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(INPUTS, fh, ensure_ascii=False, indent=2, sort_keys=False)
        fh.write("\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
